[tool.ruff]
# Python version
target-version = "py312"

# Line length
line-length = 100

[tool.ruff.lint]
# Enable specific rule sets
select = [
    # pycodestyle
    "E",  # Error
    "W",  # Warning
    
    # Pyflakes
    "F",  # Pyflakes
    
    # pyupgrade
    "UP", # pyupgrade
    
    # flake8-bugbear
    "B",  # flake8-bugbear
    
    # flake8-simplify
    "SIM", # flake8-simplify
    
    # isort
    "I",  # isort
    
    # flake8-comprehensions
    "C4", # flake8-comprehensions
    
    # Pylint
    "PL", # pylint
]

# Rules to ignore
ignore = [
    "E501",   # Line too long (handled by formatter)
    "PLR0913", # Too many arguments in function definition
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "PLR2004", # Magic value used in comparison
    "SIM108",  # Use ternary operator
    "UP007",   # Use `X | Y` for type annotations (not compatible with older Python)
]

# Exclude directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "__pycache__",
    "*.pyc",
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint.isort]
# Group imports by type
known-first-party = ["umbra"]

[tool.ruff.lint.per-file-ignores]
# Tests can use assert statements and have more relaxed rules
"tests/**/*.py" = [
    "S101",    # Use of assert
    "PLR2004", # Magic value used in comparison
    "F401",    # Unused import (common in test files)
]

# Allow print statements in main modules and scripts
"**/__main__.py" = ["T201"]
"umbra_complete.py" = ["T201", "E402", "F401"]  # Legacy file
"assessment_plan.py" = ["T201", "F401"]  # Assessment file
"test_*.py" = ["T201"]  # Test scripts

[tool.ruff.lint.flake8-bugbear]
# Allow default arguments like [], {}
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]

[tool.ruff.lint.pylint]
# Maximum number of arguments for function / method
max-args = 10
# Maximum number of local variables for function / method body
max-locals = 20
# Maximum number of public methods for a class
max-public-methods = 25